### PR TITLE
Add Arabic Translation

### PR DESCRIPTION
**Pull request by abdnh**
I've just finished translating the manual to Arabic. It would be nice if you could add it.

I've additionally added custom styles to docinfo.html to support right-to-left languages. This may be useful for other RTL languages too, like Hebrew or Persian.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Thank you very much for the huge amount of work that it surely was to translate it.

I can't update the website myself, so I'll accept the PR but leave the actual work to @mikehardy.

**Comment by mikehardy** [comment]
Wow, thanks! And actually, if you accept a docs PR, it auto-publishes, so...this is live!

https://docs.ankidroid.org/manual-ar.html
https://docs.ankidroid.org/help-ar.html

You may want to take the various other help documents and cross link them with a link to this translation as well? That is not a scalable solution if we have lots of translations but with only 4 in 10 years I can defer that problem.

My only thought is, when the user clicks for help or for the manual in the app, if their language is set to 'ar' will it resolve to these files automatically? I admit I have no idea but that would be the best situation. The links at the top of the different translations to all the others would at least allow for discovery though so your effort is available

Cheers!

**Comment by abdnh** [comment]
I may put a link in help.asc at least and open another PR for that later on.

It seems that manual links are referenced here: https://github.com/ankidroid/Anki-Android/blob/6793462d66a83d14d140a671ad74e42330e173f6/AnkiDroid/src/main/res/values/constants.xml#L140

And they are resolved depending on the app language here: https://github.com/ankidroid/Anki-Android/blob/0934f9d80090ac71730d08e9010721dc950243f9/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L545

I can open a PR on the app's repo to add Arabic links like it's done for other languages.

And thank you both for your work on AnkiDroid!

**Comment by mikehardy** [comment]
Both of those would be welcome changes @abdnh - happy to help and happy to see the big docs get translated, that's a rare event!

**Pull request merged**
