### PR TITLE
Include documentation for AdvancedStatistics plugin

### PR DESCRIPTION
**Pull request by rvanprehn**

### CODE REVIEW

**Comment by hssm** [comment]
Travis build is failing to push the changes to the website:

```
 5 files changed, 62 insertions(+), 6 deletions(-)

Counting objects: 13, done.

Delta compression using up to 32 threads.

Compressing objects: 100% (7/7), done.

Writing objects: 100% (7/7), 2.18 KiB | 0 bytes/s, done.

Total 7 (delta 5), reused 0 (delta 0)

remote: error: file write error (No space left on device)

remote: fatal: unable to write sha1 file

error: unpack failed: unpack-objects abnormal exit

To travis@ankidroid.org:/home/travis/ankidroiddocs.git

 ! [remote rejected] master -> master (unpacker error)

error: failed to push some refs to 'travis@ankidroid.org:/home/travis/ankidroiddocs.git'
```

Apparently there's no space left. Acra is dead as well.

**Comment by agrueneberg** [comment]
@hssm Woah, looks like some of the CouchDB views grew out of control. I'll try to compact some of them to fix the problem. Please send an email to the mailing list next time there are any problems with the server, I almost missed that one.

**Comment by agrueneberg** [comment]
@hssm I've compacted the views, now we've got tons of space again. Will need to add some auto-compaction in the future.

@rvanprehn Your change will be included in the next rebuild (for some reason Travis won't let me trigger it manually), thanks!

**Comment by hssm** [comment]
@agrueneberg Yeah sorry I should have let you know earlier. The Travis build sent out an email when it failed (twice, after I restarted it) and I assumed you had received the same emails. Maybe I opted in to something for that, I don't remember.

Thanks a lot for sorting everything out.

**Comment by agrueneberg** [comment]
@hssm No problem :) Looks like Travis only sends an email to "the committer and the commit author, if they are members of the repository (that is, they have push or admin permissions for public repositories, or if they have pull, push or admin permissions for private repositories)" [1]. I added myself explicitly as a recipient in 38e507923338276afc399db08f998b76a8b36b70, not sure if that stops sending mails to you guys, but we will see.

[1] https://docs.travis-ci.com/user/notifications/

**Pull request merged**
