### PR TITLE
Amend strings of links and add an annotation.

### PR DESCRIPTION
**Pull request by snowtimeglass**
The link to AnkiDroid-Nihon didn't work properly.
I don't know why, but "\" was added to the original link (by asciidoctor?).
I have deleted it.

### CODE REVIEW

**Comment by agrueneberg** [comment]
Hi @snowtimeglass,

it was me who added the "\" to the links, otherwise they would point to `https://groups.google.com/forum/<mark>!forum/anki-android`
instead of
`https://groups.google.com/forum/#!forum/anki-android`.
Seems to be some issue in asciidoctor.

Would you mind re-submitting without reverting the `\#` workaround?

Thanks,
Alex

**Comment by snowtimeglass** [comment]
Hi, Alex
Thank you for the reply.

No, I don't mind re-submitting something at all.
Should I re-submit a text in which there is an only amendment about the annotation?

Now, the link to AnkiDroid-Nihon
https://groups.google.com/forum/\#!forum/ankidroid-nihon
in AnkiDroid サポート
https://ankidroid.org/docs/help-ja.html
doesn't work properly and links to an error message as follows.

>File not in classpath roots: /\
>Error 404

Will the link work properly ?

**Comment by agrueneberg** [comment]
Oh, I didn't notice that the link to AnkiDroid Nihon doesn't work.
Escaping "#" works in all URLs but this one. Now unless I'm missing
something, this definitely looks like an issue with asciidoctor. I'll
investigate tomorrow.

Cheers,
Alex

**Comment by snowtimeglass** [comment]
Thank you.
I'm looking forward to it.
I've re-submitted a file in which there are some amendments (except for those of the link texts) . 
Please see it.

All the best,
snowtimeglass

**Comment by snowtimeglass** [comment]
Hi Alex,

Thank you always for your help.
I would like to know what the situation of the matter is now.
Is it difficult to solve the matter?

All the best,
snowtimeglass

**Pull request closed without merging**
