### PR TITLE
Add information on how to select multiple cards

### PR DESCRIPTION
**Pull request by neibez**
Small explanation with GIF added to section titled "Finding/Searching/Browsing".

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Nice! Thank you for doing this @neibez - the only issue I see is that the `manual.html` file should not be included in the change as that is auto-generated.

Can you remove the manual.html file completely? Then I'd love to merge this to explain the new feature better

**Comment by david-allison-1** [comment]
Is there a way that we could further compress the gif? It's about double the size of all the current content of our manual.

**Comment by mikehardy** [comment]
Great point @david-allison-1 - additionally, I just realized that the gif won't show up in the current release process. I think a pure text description, though disappointing vs the gif would be best at the moment. Stated differently: expand the text if needed but use text only here, no gif

**Comment by david-allison-1** [comment]
Mind if I stick in an issue for improving the release process to include new images?

**Comment by neibez** [comment]
Okay, done! Removed GIF and fixed wording.

The GIF file size was previously reduced from around 3 MB to 0.8 MB with an automated program. I don't know how to reduce the size of it any further, so I just removed it from the pull request as suggested.

**Review by mikehardy — APPROVED** [review]
I think adding images to the manual in general would be nice, but at present definitely easier to just go with text and move on. Thanks again for the change

**Comment by mikehardy** [comment]
I am certain I will forget to check this repo when I do my monthly reminder sweep since it is very very low activity so I'm posting this now - if you want to enjoy the equivalent of the internet buying you a cup of coffee for being awesome and helping AnkiDroid, please follow this :-) https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

**Pull request merged**
