### PR TITLE
document 'User Actions'

### PR DESCRIPTION
**Pull request by david-allison**
See https://redirect.github.com/ankidroid/Anki-Android/pull/15539

### CODE REVIEW

**Comment by david-allison** [comment]
CI will test rendering, 
Screenshot 2024-02-18 at 19 14 11

**Review by mikehardy — COMMENTED** [review]
Should there be some text to tie in with the ability to map them to gestures or action bar buttons?

Like, 

Once defined in your card template, these User Actions may be used by either mapping them to gestures in the Gestures area of Settings, or by enabling the User Action buttons you want in the Action Bar area of Settings

 ?

**Comment by david-allison** [comment]
This is a subheading of https://ankidroid.org/#gestures, so it didn't seem worthwhile

This page will likely be linked to from a "more info" in gestures, so the context is provided externally otherwise

**Review by mikehardy — APPROVED** [review]
I'll reverse reviewer's choice and go instead with implementor's choice
works for me!

**Pull request merged**
