### PR TITLE
Change translated words

### PR DESCRIPTION
**Pull request by snowtimeglass**
「PC版Anki」-->「PCソフトAnki」、
「説明書」-->「マニュアル」

### CODE REVIEW

**Comment by agrueneberg** [comment]
Could you please try to submit this without the two rename commits? There is still #4 and I haven't had time to find a solution for it yet.

**Comment by snowtimeglass** [comment]
Certainly.
Thank you for the advice.
I'll try to do.

I'm sorry for renaming the name of the file.
I'm not accustomed to using Github.

**Comment by snowtimeglass** [comment]
I'm sorry.
I can't solve it by myself.
Would you please tell me how to do?

(I would like to make [my "master" branch](https://github.com/snowtimeglass/ankidroiddocs)
reset and identical with [the original](https://github.com/ankidroid/ankidroiddocs), if possible...)

**Comment by agrueneberg** [comment]
Sure, no problem. git is not the easiest tool to grok.

Be aware that all your changes that have not been merged into the original repository will be **removed** by running the following commands, so better make a copy of your files or clone your repository again into a different directory:
1. For convenience, create an alias to the original repository (I usually call it `upstream`, if you pick a different name such as `ankidroiddocs` you have to replace every occurrence of `upstream` with `ankidroiddocs`): `git remote add upstream https://github.com/ankidroid/ankidroiddocs.git`
2. Get the changes from the original repository: `git fetch upstream`
3. Overwrite your copy with the original: `git reset --hard upstream/master`
4. Overwrite your repository on GitHub with your local repository: `git push origin master -f`

After that you can apply your changes again ([ideally in a branch](http://nvie.com/posts/a-successful-git-branching-model/), otherwise you will run into the same issue again at some point, but that's a whole different topic...) and create another pull request.

This is just one of many ways. There is also no shame in just deleting your repository and forking the original again. I have done that countless times when I was new to git.

[Have you tried modifying the pages directly in GitHub?](https://github.com/ankidroid/ankidroiddocs/edit/master/help-ja.txt) This seems to be the easiest options to me and doesn't require a whole lot of git knowledge.

**Comment by nicolas-raoul** [comment]
Yes, as Alex said, the super-easy way is:
1. Delete your fork
2. Fork again
3. Apply your modifications and send pull request

**Comment by snowtimeglass** [comment]
Thank you, Alex and Nicolas!
That's very thoughtful of you!

Thanks to you,
I seem to have succeeded in  making my "master" identical with the original repository!
I'll send pull request again.

>After that you can apply your changes again (ideally in a branch, otherwise you will run into the same issue again at some point

Yes, I've learned a lesson from this failure. Thank you for the advice.

>Have you tried modifying the pages directly in GitHub? This seems to be the easiest options to me and doesn't require a whole lot of git knowledge.

Yes, I've done. 
As you says, it is far easier to do so. 
I'll edit files  in that way in many situations in the future.
As I mistakenly edited my "master", I tried to revise it by using GitHub Desktop.

The advice about deleting a repository relieved my mind. Thank you.

Thanks to you, I've learned a lot.
It's indeed "kega no koumyou (an unexpected success born out of a failure)" :-)

**Pull request closed without merging**
