### PR TITLE
add 'alpha testing' section and image

### PR DESCRIPTION
**Pull request by david-allison**
Some users were confused by the instructions. Leaving it to CI to show a preview of the docs to verify.

png optimized with `oxipng`

### CODE REVIEW

**Comment by david-allison** [comment]
Screenshot 2023-04-25 at 13 31 19

**Comment by david-allison** [comment]
Better: Screenshot 2023-04-25 at 14 19 54

**Comment by david-allison** [comment]
Making the image clickable to reduce confusion

**Review by mikehardy — APPROVED** [review]
Nice!

**Pull request merged**
