### PR TITLE
Added note about !Recovered deck for #5932

### PR DESCRIPTION
**Pull request by david-allison-1**
GitHub preview didn't preview the [admonition](https://asciidoctor.org/docs/asciidoc-writers-guide/#admonitions) correctly. 

Would like to confirm that this will work when pushed to live.

### CODE REVIEW

**Comment by mikehardy** [comment]
cross-linking to ankidroid/Anki-Android#5932 and ankidroid/Anki-Android#5949

**Comment by mikehardy** [comment]
haha gogogogogo

**Comment by david-allison-1** [comment]
Sorry, thanks!

**Comment by david-allison-1** [comment]
Section in the manual for later verification: https://docs.ankidroid.org/manual.html#_advanced_actions

**Pull request merged**
