### PR TITLE
Snowtimeglass patch 1

### PR DESCRIPTION
**Pull request by snowtimeglass**
Change translated words

### CODE REVIEW

**Comment by agrueneberg** [comment]
Thanks!

**Comment by timrae** [comment]
Thank you! By the way, you're welcome to modify the original English manual as well if you find places which need improvement. I will do a final "native check", so don't worry if the English is not perfect.

**Comment by snowtimeglass** [comment]
Alex, 
Thank you for your support! 
Your advice was really helpful and it reassured me.

Tim, Thank you!
I am very glad that you said that for me.
As you said, I'll try to alter the English manual (relying on your check) if I think it may be desirable to do so.

I am interested in  adding image files as well as editing the text.
e.g. buttons

ic_menu_refresh
ic_menu_night
ic_menu_edit

Would such alternations be welcomed?

**Comment by timrae** [comment]
Yes I think having inline icons would be useful if you can make it blend in
well with the existing documentation.
You're also welcome to change the English strings in AnkiDroid itself, or
the icons, or anything you like really ;)

See the following link for detailed information on where to find the icons
and strings in the AnkiDroid source code
<https://github.com/ankidroid/Anki-Android>:
https://code.google.com/p/ankidroid/wiki/DevelopmentDocumentation

**Comment by timrae** [comment]
I meant the "Files: Where to find what" section of that page by the way

**Comment by snowtimeglass** [comment]
Thank you!
I would like to try it some day.

Thanks for your guidance,
I found icons in %root/res/drawable-**dpi.

**Pull request merged**
