### PR TITLE
Added Keyboard shortcuts

### PR DESCRIPTION
**Pull request by david-allison-1**
* Added Keyboard shortcuts. 
* Made beta testing a h2 instead of a h3

https://asciidoctor.org/docs/user-manual/#keyboard-shortcuts

⚠️ This has not been rendered via asciidoctor to test whether the macro works.

Please squash and merge once accepted.

### CODE REVIEW

**Comment by mikehardy** [comment]
If you push this again, we'll get a fully rendered site as an artifact, so we can check it out

It'll be hanging off the workflow run like this:

Screenshot from 2020-08-27 15-38-21

...and if that works then all future PRs will be rendered for inspection as well :-)

**Comment by mikehardy** [comment]
@david-allison-1 all you need to do is re-push then and we'll have a check, I created a whole new github workflow to do it and I'm excited to see if it works

**Comment by david-allison-1** [comment]
Manual appears unchanged

**Comment by mikehardy** [comment]
Yeah, so I found the problem :facepalm: 

@david-allison-1 re-push ?

```
mike@isabela:~/work/AnkiDroid/ankidroiddocs (master) % git show -p
commit 6e6066aeef91c1335c0979819cbb86a1ede7fa38 (HEAD -> master, origin/master, origin/HEAD)
Author: Mike Hardy <github@mikehardy.net>
Date:   Sun Aug 30 11:41:50 2020 -0500

    Allow fetch of triggering git SHA, not always master
    
    The easy answer to the question "why did the PR pull tip of main branch?"

diff --git a/.github/workflows/render_docs.yml b/.github/workflows/render_docs.yml
index 3a59ea6..fa0579f 100644
--- a/.github/workflows/render_docs.yml
+++ b/.github/workflows/render_docs.yml
@@ -10,10 +10,8 @@ jobs:
     name: 'Render Docs'
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-        with:
-          ref: 'master'
-          fetch-depth: 0
+      - name: Git Checkout
+        uses: actions/checkout@v2
 
       - name: Install Asciidoctor
         run: |

```

**Comment by david-allison-1** [comment]
@mikehardy Still needs something else

**Comment by david-allison-1** [comment]
Looks good

image

**Pull request merged**
