### PR TITLE
Prepare 2.14.0 release

### PR DESCRIPTION
**Pull request by mikehardy**

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Seems to be missing https://github.com/ankidroid/Anki-Android/pull/7585
Also, it may be worth noting that the translation process was made easier thanks to screenshot by rfn0.

**Comment by mikehardy** [comment]
the PR you mention was add shortcut to home screen I think? I believe it was in there
rfn0 definitely deserves some recognition, maybe mention them specifically in the tweet announcement for the new version "AnkiDroid 2.14.0 is out with tons of features (https://github.com/ankidroid/Anki-Android/pulls?q=is%3Aclosed+milestone%3A%222.14+release%22+is%3Apr) - and we want to specifically thank (link to rnf0 here?) for their incredible work improving our translations. Happy Reviewing!"

Or similar, I only wrote text because I feel like if I suggest something I should actually propose the thing but you can literally do anything you like, except you should tweet the new release once we promote it to stable channel

**Comment by mikehardy** [comment]
Most importantly, the release is already compiled with the changelog in it :sweat_smile:

**Comment by Arthur-Milchior** [comment]
Oh, sorry, I didn't understood "Add deck shortcut". You're right. All of my two functional changes are mentioned :p 

Concerning translation, I believe that the thing I really want to emphasize at some point is that it is becoming easier to translate, hinting people to come do it, or may be even give a second try if they quitted before

**Pull request merged**
