### PR TITLE
V2.9 preview - rebase from master and add entries for 2.9 PRs

### PR DESCRIPTION
**Pull request by mikehardy**
I just did a rebase from master (it was clean), then added information from all the PRs on github since what I think was the 2.9 alpha cycle release start

### CODE REVIEW

**Comment by mikehardy** [comment]
@timrae this one isn't as important as the other one but I'm thinking forward to 2.9 and a release is a lot more than just code, I think this is necessary as well?

**Comment by timrae** [comment]
We don't normally do release notes for alpha / beta releases. I don't really feel it's sustainable, so I'd prefer to just put that information on the forum for now and keep this repo focused on what is going to be shown at the final release.

**Comment by mikehardy** [comment]
@timrae this was the docs PR I had staged, needs a refresh, but does contain a chunk of work in the form of me scanning all the changes from first 2.8 branching through whenever I last committed here. Shouldn't take long to get it up to date if you want me to build on it?

**Comment by timrae** [comment]
Yes please, thank you @mikehardy!

**Comment by mikehardy** [comment]
sweet - I'll look through the commits sense then and try to shape this up
I suppose we'll also need verbiage for mathjax, multi-select, v2 scheduler, and updated import/export docs

**Comment by mikehardy** [comment]
sorry I didn't get to mopping this up but I think the commit I just looked at includes all this, so I'm closing for now but the material is of course always here

**Pull request closed without merging**
