### PR TITLE
release: proposed docs for 2.16.4 release

### PR DESCRIPTION
**Pull request by mikehardy**
I'm being playful on purpose, these are read by real people and gentle humor is in my opinion the most effective way to keep people reading - a light sense of humor + gratitude is the tone I generally go for in all public ankidroid communications

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Nothing about API 33?

**Comment by mikehardy** [comment]
> Nothing about API 33?

I thought about it, but I have a criteria I use before I say anything to users (or at least, I try to use it, I'm human) and it's based on the THINK public comments rules:

T - is it True?
H - is it Helpful?
I - is it Inspiring?
N - is it Necessary?
K - is it Kind?

I felt like API33 fails the helpful/necessary checks because really, does knowing we updated to API32 + 33 actually *mean* anything to them? Was anyone waiting for it, as a fix or anything?

IMHO, no, it's not actually useful or actionable information - it was certainly necessary and will make sure we *maintain* our position in the play store, but I don't think any users will care.

Now, if we had fallen out of the store and this got us back in, that's news!

Anyway, that's my thought process, and why I left it out even though arguably it drove the release 😆 

If you disagree just post a suggestion that edits it in on review - I don't take release notes that seriously on purpose so I can maintain a light tone, and I feel the same about what goes in, you want it, you got it.

Cheers

**Comment by mikehardy** [comment]
(note my mention of more anki desktop was - I thought - useful as the obsessive scheduler-debater types want that v3, they want that custom scheduling etc - and I know they are actually waiting there, watching....)

**Review by david-allison — APPROVED** [review]
Passes all the tests aside from 'necessary', I don't feel strongly, so inaction is the best action

**Pull request merged**
